In [2]:
import glob
import pandas as pd
import re
from tqdm import tqdm
from konlpy.tag import Mecab

import warnings
warnings.filterwarnings("ignore")

In [8]:
lis = glob.glob('1960~1999 네이버 뉴스 라이브러리/txt/*.txt')
df = pd.DataFrame(columns=["제목","언론사","일자","키워드"])

for name in lis:
    name_list = name.split("_")
    article = name_list[0].split("/")[2]
    press = name_list[1].split("1")[0]
    date = re.sub("[^0-9]" ,"", name_list[1])
    f = open(name, 'r')
    text = str(f.readlines()[2:])
    tmp = pd.DataFrame({"제목": [article], 
                       "언론사": [press], 
                       "일자": [date],
                       "키워드": [text], 
                       })
    df = pd.concat([df, tmp])
    
df.reset_index(inplace=True, drop=True)
df.head(10)

,제목,언론사,일자,키워드
0,자유711일그여자사람잡네,동아일보,19780904,"['自 由 (자유) 7~1 - 일 \n', '「그여자 사람잡네」 \n', '극단 「..."
1,신병비관50대부인아파트서투신자살,동아일보,19830316,"['身 病 (신병) 비관 50대부인 \n', '아파트서 투신 自 殺 (자살) \n'..."
2,중년의의학121뇌와마음,동아일보,19761201,"['中年 (중년) 의 医学 (의학) \n', '(121) \n', '脳 (뇌) 와마..."
3,관계법4월국회제정정신질환자신고의무화,동아일보,19830330,"['�係法 (관계법) 4월�� (국회) 제정 \n', '정신疾患者 (질환자) 申告 ..."
4,조울증으로자살유발,조선일보,19780811,"['「조울증」 으로 自殺 (자살) 유발 \n', '金 (김)박사 事件 (사건) \n..."
5,청소년전담진료과늘어난다,조선일보,19911124,"['청소년 전담진료과 늘어난다 \n', '입시 불안- 조울증등 상담 - 치료 \n'..."
6,질병과싸우는명의들의휴먼스토리,조선일보,19990208,"['질병과 싸우는 名� (명의)들의 휴먼스토리 \n', 'EBS TV,12일부터 5..."
7,의학에세이203정신병과결혼,동아일보,19750805,"['精神病(정신병) 과結婚 (결혼) \n', '<203> \n', '遺� (유전) ..."
8,가수김광석자살,조선일보,19960107,"['가수 金光石 (김광석) 자살 \n', '「나의 노래」 . 「거리에서」 란노래를 ..."
9,무명가수리자로엡정상도전,조선일보,19940728,"['무명가수 리자 로엡 정상도전 \n', '데뷔곡 「stay」 빌보드 2위랭크 \n..."

In [9]:
lis = glob.glob('1965~1989 중앙일보/*.txt')
jungang_df = pd.DataFrame(columns=["제목", "언론사", "일자", "키워드"])

for name in lis:
    name_list = name.split("-")
    article = name_list[0].split("/")[1]
    article = re.sub("_", " ", article)
    press = "중앙일보"
    date = name_list[1].split("_")[0]
    date = re.sub("[^0-9]", "", date)
    f = open(name, 'r')
    text = f.read()
    tmp = pd.DataFrame({"제목": [article], 
                       "언론사": [press], 
                       "일자": [date],
                       "키워드": [text], 
                       })
    jungang_df = pd.concat([jungang_df, tmp])
    
jungang_df.reset_index(inplace=True, drop=True)
jungang_df.head(10)

,제목,언론사,일자,키워드
0,정신질환과 천재성 관련없다,중앙일보,19860730,천재 음악가나 문학인들을 흔히 괴롭혀왔던 정신착란증 등의 신경질환증세는 그들의 예술...
1,"보사부,모자보건법시행령 공포 전염성 지...",중앙일보,19730528,인공임신중절수술의 허용한계와 시기 및 불임 수술대상자 등을 규정한 모자보건법 시행령...
2,정신병 「출퇴근치료」뿌리내린다.,중앙일보,19860624,"「적극적 사고방식」,「또 다른 자기발견」-.여남은 명의 남자들이 차분한 자세로 한 ..."
3,유력지 WP의 여사장「캐더린·그레이엄」여사,중앙일보,19741119,「워싱턴·포스트」지(중앙일보 특약사)사장인「캐더린·그레이엄」여사를 두고「번디」전 미...
4,무더위 식혀 주는「경쾌한 소품」쏟아져,중앙일보,19770801,윤=무더위를 감안한 편집자의 시도인지 이 달에는 경쾌한 소품들이 많이 눈에 띄는군요...
5,코 심하게 고는 사람 고혈압·심부전 조심,중앙일보,19870324,코 잘고는 사람은 고혈압이나 심부전증을 조심하라. 이 경고는 일본 천섭현 종합 병원...
6,"″약물정체는 신경안정제〃 『주간문춘』,...",중앙일보,19820318,【동경=신성순 특파원】18일 발매된 25일자 주간문춘은「가네히라」회장이 약물공작에 ...
7,O형 혈액형에 조울증 많다,중앙일보,19810729,정신병 중 큰 부분을 차지하고 있는 조울증이 일반적으로 활달하고 활동력이 강한 것으...
8,우울증 앓던 두주부 자살,중앙일보,19830316,심한 우울·조울증세에 시달리던 주부 2명이 자살했다.\n▲16일 상오5시30분쯤 서...
9,공포의「현대병」 꼬리무는 살인과 정신병...,중앙일보,19681128,순창과 예산에서 27일 2명의 정신병자가 도끼와 식칼로 11명의 인명을앗은 끔찍한 ...

In [11]:
lis = glob.glob('2000~2024 조선일보/*.txt')
josun_df = pd.DataFrame(columns=["제목","언론사","일자","키워드"])

for name in lis:
    name_list = name.split("-")
    for _ in range(len(name_list)):
        if name_list[1][0].isdigit()==False:
            name_list[0] = name_list[0] + "_" + name_list[1]
            del(name_list[1])
    article = name_list[0].split("/")[1]
    press = "조선일보"
    date = name_list[1].split("_")[0]
    if date[0].isdigit()==False:
        date = name_list[1].split("_")[1]
        article = article + name_list[1].split("_")[0]
    date = re.sub("[^0-9]", "", date)
    article = re.sub("_", " ", article)
    f = open(name, 'r')
    text = f.read()
    tmp = pd.DataFrame({"제목": [article], 
                       "언론사": [press], 
                       "일자": [date],
                       "키워드": [text], 
                       })
    josun_df = pd.concat([josun_df, tmp])
    
josun_df.reset_index(inplace=True, drop=True)
josun_df.head(10)

,제목,언론사,일자,키워드
0,"[어저께TV] 삼시세끼 , 박신혜는 옥빙구도...",조선일보,20150523,[OSEN=박현민 기자] 그룹 2PM 옥택연이 박신혜의 매력에 흠뻑 빠졌다. 만면에...
1,"김성태 폭행범,징역 1년 구형에 난 히...",조선일보,20180604,지난 5일 김성태 자유한국당 원내대표를 폭행한 김모씨가 당직자들에게 제압당하고 있다...
2,"장근석 팬클럽, 악플러 너희 이제 다 죽...",조선일보,20181123,배우 장근석\n한류스타 장근석(31)의 팬들이 악플러를 경찰에 고발했다. 23일 소...
3,"美펜타곤 총기범, 정신질환 병력에 음...",조선일보,20100306,4일(현지시간) 미국 펜타곤(국방부 청사) 입구에서 총기를 난사한 존 패트릭 베델(...
4,"대법원, 김승연 한화 회장 상고심 26일...",조선일보,20130923,구급차를 탄 채 항소심 선고 공판을 받기 위해 법원에 출두하고 있는 김승연 한화 회...
5,손예진 공범 개봉 앞두고 조울증 상태‥...,조선일보,20131014,손예진 영상 캡처\n배우 손예진이 조울증 상태라고 밝혔다.\n\n손예진은 14일 방...
6,"계산 안 하고 우유 마시던 30대 女, 계산 요구...",조선일보,20211123,계산을 하지 않고 편의점에서 우유를 집어 들어 마시다 계산을 요구하는 아르바이트생에...
7,살생부 엔 28명이… 이것들 다 죽여야 ᄌ...,조선일보,20150919,17일 서울 성동구 트렁크 살인사건 용의자 김일곤이 성동경찰서로 압송되고 있다. 김...
8,"이대통령, 국무회의서 난상토론…16개 안거...",조선일보,20090630,이명박 대통령은 30일 오후 6시 청와대 본관 세종실에서 제27회 국무회의를 주재하...
9,"김홍파x장나라, 교도소서 만난 부녀…소이현...",조선일보,20240218,종영까지 단 3회를 남겨둔 ‘나의 해피엔드’ 장나라와 김홍파가 긴장감과 먹먹함이 교...

In [13]:
bigkinds_df = pd.DataFrame()
lis = glob.glob('1990~2024 빅카인즈/*.xlsx')

for data in lis:
    tmp = pd.read_excel(data, engine="openpyxl")
    tmp = tmp[["제목","언론사","일자","키워드"]]
    bigkinds_df = pd.concat([bigkinds_df, tmp])
    
bigkinds_df.drop_duplicates(inplace=True)
bigkinds_df.reset_index(inplace=True, drop=True)
bigkinds_df.tail(20)

,제목,언론사,일자,키워드
3892,"""편견 허문다""... 정신 질환을 다루는 드라마들",한국일보,20241113,"편견,정신,질환,드라마들,기억상실,해리성,정체,장애,드라마,드라마,정신,질환,콘텐츠..."
3893,"폰-술-쇼핑 등 중독은 뇌회로 바꾸는 질환 뇌자극 통한 치료 연구중[이진형의 뇌, ...",동아일보,20241113,"쇼핑,중독,뇌회,질환,뇌자극,치료,이진형,우주,행동,물질,중독,시대,중독,사실,인식..."
3894,[직설]태어나길 잘했다,경향신문,20241111,"얼마,생일,생일,직전,강의,유전자,사회학,착상,검사,유전,진단,한정적,질병,검사,검..."
3895,‘들뜨고 가라앉는 마음’ 겪는 환자에게 “의지 부족 탓하면 역효과” [건강한겨레],한겨레,20241108,"마음,환자,의지,부족,역효과,건강한겨레,하루,감정,기복,사람,조울증,양극성,장애,조..."
3896,"정신 장애 있는 자녀만 참관한 압수수색 대법 “위법, 실질적 참여 이뤄져야”",동아일보,20241028,"정신,장애,자녀,참관,압수수색,대법,위법,실질,참여,절차,이해,정도,정신,장애,가족..."
3897,"무속인 왜 안 좋게 보냐고? ""돈만 좇는 모습에 실망""",한국일보,20241022,"무속,모습,실망,방치,믿음,무속,대해부,본보,무당,설문,조사,현실,바람무속,부정적,..."
3898,[기억할 오늘] 내 (늙은) 몸을 논평하지 말아 달라,한국일보,20241021,"논평,달라,피셔,10.21,캐리,영화,스타워즈,3부,오리지널,에피소드,희망,시작,스..."
3899,당신이 어느 날 눈뜨니 정신병원에 묶여 있다면,한겨레,20241019,"정신병원,세카이노오와리,일본어,세상,일본,음악,사람,유명,밴드,메인,보컬,작사,작곡..."
3900,[단독] ‘251시간 강박 사망’ 춘천 정신병원장 주치의 벌금형,한겨레,20241018,"사망,시간,강박,춘천,정신,병원장,주치,벌금형,춘천예현병원,입원,환자,격리실,침대,..."
3901,"“페미는 맞아야 돼” 진주 편의점 폭행, ‘여성 혐오 사건’ 첫 인정 판결",한국일보,20241017,"페미,폭행,진주,편의점,사건,여성,혐오,인정,판결,재판부,여성,근거,혐오,편견,범행..."
3902,‘편의점 숏컷 여성혐오 폭행’ 항소심도 징역 3년 “심신미약 인정돼 참담”[플랫],경향신문,20241016,"편의점,숏컷,여성,혐오,폭행,항소심,징역,심신미약,인정,참담,플랫,경남,진주,머리,..."
3903,"편의점 여성혐오 폭행 20대, 항소심도 징역 3년 ‘심신미약 인정에 참담’ 여성단...",경향신문,20241015,"편의점,여성,혐오,폭행,항소심,징역,심신미약,인정,참담,여성,단체,반발,경남,진주,..."
3904,“페미는 맞아도 돼” 진주 편의점 알바 폭행한 20대 항소심도 징역 3년,서울신문,20241015,"페미,진주,편의점,알바,폭행,항소심,징역,재판부,여성,근거,혐오,편견,범행,동기,머..."
3905,가족들 위해 신내림 받았지만... 두 딸은 차례로 정신병에 걸렸다,한국일보,20241011,"가족들,차례,정신병,방치,믿음,무속,엄마,남자영험,무속인,비용,전달,신엄마,의심,행..."
3906,“1명이 나를 비난한다고 고민 말고 나머지 9명과 잘 지내는 훈련해야”,서울신문,20241010,"1명,비난,고민,나머지,훈련,정신건강,세계,정신,건강,명의,신영철,교수,마음,건강,..."
3907,조현병 의사가 수술을? 화들짝 의협 “다 결격사유 되는 건 아냐”,서울신문,20241002,"조현병,의사,수술,의협,결격사유,5년,진단,연평균,의사,정신,질환,의협,치료,가능,..."
3908,"""날 무시해?"" 50대 마트 직원 27번 찌른 20대에 징역 7년",한국일보,20241002,"무시,마트,직원,20대,징역,근무자,범행,평소,조울증,정신,질환,영향,자신,무시,오..."
3909,“무시했다고 착각” 마트 계산원 27차례 찌른 20대 징역 7년,조선일보,20241002,"무시,착각,마트,계산원,차례,7년,징역,강원,횡성,마트,계산원,여성,흉기,27차례,..."
3910,“나 무시했어?” 복수심에 마트 계산원 27회 찌른 20대,서울신문,20241002,"무시,복수심,27회,마트,계산원,20대,혐의,살인,미수,1심,선고,징역,강원,횡성,..."
3911,[함영준의 마음PT] 한 집 건너 정신과 예약 만원사례인 이유,조선일보,20241001,"정신,예약,만원,사례,걱정,시대,정신,역사,우리나라,요즘,자살,・우울증,급증,의원들..."

In [14]:
df = pd.concat([df, jungang_df])
df = pd.concat([df, josun_df])
df = pd.concat([df, bigkinds_df])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4927 entries, 0 to 3911
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제목      4927 non-null   object
 1   언론사     4927 non-null   object
 2   일자      4927 non-null   object
 3   키워드     4927 non-null   object
dtypes: object(4)
memory usage: 192.5+ KB

In [15]:
df["text"] = df["키워드"].str.replace("[^가-힣|0-9]","", regex=True)
df.head(10)

,제목,언론사,일자,키워드,text
0,자유711일그여자사람잡네,동아일보,19780904,"['自 由 (자유) 7~1 - 일 \n', '「그여자 사람잡네」 \n', '극단 「...",자유71일그여자사람잡네극단자유는7일부터11일까지오후4시와7시반동아연극상참가작품로벨토...
1,신병비관50대부인아파트서투신자살,동아일보,19830316,"['身 病 (신병) 비관 50대부인 \n', '아파트서 투신 自 殺 (자살) \n'...",신병비관50대부인아파트서투신자살16일새벽5시반경서울영등포구당산동3가평화아파트동앞아스...
2,중년의의학121뇌와마음,동아일보,19761201,"['中年 (중년) 의 医学 (의학) \n', '(121) \n', '脳 (뇌) 와마...",중년의의학121뇌와마음외인성정신병은뇌질환치료부터불안우울은뇌와무관설이상복예전에우리마음...
3,관계법4월국회제정정신질환자신고의무화,동아일보,19830330,"['�係法 (관계법) 4월�� (국회) 제정 \n', '정신疾患者 (질환자) 申告 ...",관계법4월국회제정정신질환자신고의무화위해우려땐유치명령종합병원정신과꼭설치정신장애범죄형면...
4,조울증으로자살유발,조선일보,19780811,"['「조울증」 으로 自殺 (자살) 유발 \n', '金 (김)박사 事件 (사건) \n...",조울증으로자살유발김박사사건김희규교수실종사건은숱한곡절을거듭한끝에자살로판명됐다경찰은당초...
5,청소년전담진료과늘어난다,조선일보,19911124,"['청소년 전담진료과 늘어난다 \n', '입시 불안- 조울증등 상담 - 치료 \n'...",청소년전담진료과늘어난다입시불안조울증등상담치료부모교육단체활동주선병행하기도청소년기의특수...
6,질병과싸우는명의들의휴먼스토리,조선일보,19990208,"['질병과 싸우는 名� (명의)들의 휴먼스토리 \n', 'EBS TV,12일부터 5...",질병과싸우는명의들의휴먼스토리12일부터5부작현대의학의영웅들방송여고생케이재미슨은자기가혹...
7,의학에세이203정신병과결혼,동아일보,19750805,"['精神病(정신병) 과結婚 (결혼) \n', '<203> \n', '遺� (유전) ...",정신병과결혼203유전과관계없고잘치료하면얼마든지완치가능남구에서온젊고유망한한청년이급성정...
8,가수김광석자살,조선일보,19960107,"['가수 金光石 (김광석) 자살 \n', '「나의 노래」 . 「거리에서」 란노래를 ...",가수김광석자살나의노래거리에서란노래를유행시켰던인기가수김광석씨32가6일새벽4시쯤서울시마...
9,무명가수리자로엡정상도전,조선일보,19940728,"['무명가수 리자 로엡 정상도전 \n', '데뷔곡 「stay」 빌보드 2위랭크 \n...",무명가수리자로엡정상도전데뷔곡빌보드2위랭크자기앨범한장없이이변연출아직정식앨범도내지못한생...

In [16]:
def tokenize(sentence:pd.Series):

    tokenizer = Mecab()
    tokenized=[]
    temp = tokenizer.nouns(sentence)
    temp = [word for word in temp] 
    tokenized.append(temp)
    
    for token in tokenized:
        string = ""
        for num in range(len(token)):
            if (len(token[num])>=2) & (num != len(token)-1):
                string += token[num] + ","
            elif num == len(token)-1:
                string += token[num]
    return string

In [17]:
df["키워드"] = df["text"].apply(tokenize)
df["일자"] = pd.to_datetime(df["일자"])
df.drop("text", axis=1, inplace=True)

In [18]:
import pyBigKinds as pbk

pbk.keyword_dataframe(df).head(20)

     단어     빈도
0    정신  16763
1    환자   8405
2    치료   8250
3    장애   8002
4    사람   7064
5   조울증   6711
6    병원   6153
7    질환   5171
8    건강   4628
9    자신   4572
10   사회   4525
11  우울증   4353
12   경찰   4001
13   자살   3604
14   입원   3075
15   가족   3012
16   사건   2901
17   상태   2887
18   교수   2823
19   생각   2778

In [20]:
weighted = pbk.tfidf(df)
weighted.head(20)

     단어          빈도
0    정신  230.918906
1    환자  159.148783
2    장애  136.659616
3    치료  135.562218
4    경찰  122.831430
5    병원  111.503557
6    질환  103.377630
7   우울증   99.236625
8    사람   99.101182
9   조울증   96.054378
10   건강   90.434941
11   자살   85.789941
12   사회   80.313969
13   범행   77.994620
14   자신   76.029513
15   입원   73.040390
16   혐의   72.711788
17   교수   67.089890
18   사건   66.676342
19   조사   65.997486

In [ ]:
df.to_excel("model/data/bipolar_disorder_all.xlsx", index=False)