In [1]:
import glob
import pandas as pd
import re
from tqdm import tqdm
from konlpy.tag import Mecab

import warnings
warnings.filterwarnings("ignore")

In [4]:
lis = glob.glob('1960~1999 네이버 뉴스 라이브러리/txt/*.txt')
df = pd.DataFrame(columns=["제목","언론사","일자","키워드"])


for name in lis:
    name_list = name.split("_")
    for _ in range(len(name_list[:-3])):
        name_list[0] = name_list[0] + "_" + name_list[1]
        del(name_list[1]) 
    article = name_list[0].split("/")[2]
    press = name_list[1].split('1')[0]
    date = re.sub("[^0-9]" ,"", name_list[1])
    f = open(name, 'r')
    text = str(f.readlines()[2:])
    tmp = pd.DataFrame({"제목": [article], 
                       "언론사": [press], 
                       "일자": [date],
                       "키워드": [text], 
                       })
    df = pd.concat([df, tmp])
    
df.reset_index(inplace=True, drop=True)
df.head(10)

,제목,언론사,일자,키워드
0,심프슨교수「高血壓(고혈압)의_藥物(약물)_요법」,경향신문,19791016,"['심프슨교수 「高血�(고혈압) 의 薬物 (약물) 요법」 \n', '빠른진단이 最善..."
1,갱년기엔_달리기-등산을,조선일보,19950113,"['갱년기엔 달리기-등산을 \n', '산소 섭취하는유산소운동과근력 증강시키는하중운동..."
2,불행한_가정은_질병_원인된다,조선일보,19960508,"['불행한 가정은 \n', '질병 원인된다 \n', '사별우울증 = 무력감 겪어 \..."
3,PC통신_안방마님_주부파워_막강,조선일보,19970517,"['PC통신 안방마님 \n', '주부파워 막강 \n', '매년 3배 증가··· 재테..."
4,주부頭痛(두통)82%가「마음의_病(병)」때문,동아일보,19830628,"['주부頭痛 (두통) 82%가 「마음의 病 (병)」 때문 \n', '夫婦 (부부) ..."
5,“웃음은_人生(인생)의_힘”美(미)코미디언‘마ᄀ...,조선일보,19990930,"['""웃음은 人生 (인생) 의 힘""美 (미) 코미디언\'마거릿 조\'再起 (재기) ..."
6,신경정신과_鄭聖德(정성덕)박사_설문조사_...,경향신문,19820621,"['신경정신과 �聖徳 (정성덕)박사 설문조사 \n', '主婦 (주부) 우울증이 늘고..."
7,프랑스의_새_골칫거리_컴퓨터사고_人災(인재)ᄀ...,경향신문,19890401,"['프랑스의 새 골칫거리 컴퓨터사고 \n', '人災 (인재)가 대부분 \n', '人..."
8,불새(474),조선일보,19800730,"['불새 \n', '(474) \n', '野 (야) 火 (화) 26 (㉖) \n',..."
9,청소년_우울증_논문발표,조선일보,19930304,"['청소년 우울증 논문발표 \n', '우리나라 어린이와 청소년들은미국학생들보다 우울..."

In [5]:
lis = glob.glob('1965~1989 중앙일보/*.txt')
jungang_df = pd.DataFrame(columns=["제목", "언론사", "일자", "키워드"])

for name in lis:
    name_list = name.split("-")
    article = name_list[0].split("/")[1]
    article = re.sub("_", " ", article)
    press = "중앙일보"
    date = name_list[1].split("_")[0]
    date = re.sub("[^0-9]", "", date)
    f = open(name, 'r')
    text = f.read()
    tmp = pd.DataFrame({"제목": [article], 
                       "언론사": [press], 
                       "일자": [date],
                       "키워드": [text], 
                       })
    jungang_df = pd.concat([jungang_df, tmp])
    
jungang_df.reset_index(inplace=True, drop=True)
jungang_df.head(10)

,제목,언론사,일자,키워드
0,중년의 주부 모습 연극으로 본다 마당그...,중앙일보,19850409,가사 노동을 주제로 한 가정 주부들의 마당극 『이 세계 절반은 나』가 오는 5월 1...
1,예시「커트라인」제의 폐지,중앙일보,19771031,79학년도부터 대학입시제도에 상당한 변동이 있을 것으로 예고되었다. 28일 국회문공...
2,성정순 57·이대체육대교수,중앙일보,19840707,『수영은 지금까지 나를 아무탈없이 지켜온 건강파수꾼입니다. 계절에 관계없이 취미와 ...
3,358 편두통치료,중앙일보,19830727,▲편두통의 치료=우리나라에서 심한 편두통때 우황청심환이나 침으로 머리를 따는 치료를...
4,대학생은 피로하다 한국대학생의 당면문제,중앙일보,19711204,한국의 대학생들은 늘 피곤해있다. 그들이 피곤해하는 요인은 주로 「사치풍조가 높아지...
5,나의 고교 시절 한승헌,중앙일보,19710414,"고등학교에 들어간지 두달쯤 되었을 때, 6·25가 터졌다. 무기한의 휴교가 선포되자..."
6,"홍강의교수, 어린이 불안장애환자 90명 ᄇ...",중앙일보,19841206,"불안을 주증상으로 하는 아동의 정서장애, 즉 불안장애 아동들이 눈에띄게 늘어나면서 ..."
7,(15) 술과 정신질환(5) 장환일(경희대벼...,중앙일보,19861114,우리나라도 세계적인 추세에 따라 여성 음주자가 늘고 있다. 그 결과 요즘은 알콜중독...
8,"임옥상 개인전을 보고, 유흥준 미술평ᄅ...",중앙일보,19840607,80년대 새로운 미술운동의 작가로 크게 주목받아 온 임옥상 (36 전주대교수) 의 ...
9,스트레스 역이용 생활의 활력소로 심리사...,중앙일보,19870626,불안·우울·갈등·초조·의욕 상실· 질병등 온갖 심신장애를 일으키는 스트레스.\n삶 ...

In [6]:
lis = glob.glob('2000~2024 조선일보/txt/*.txt')
xlsx = pd.read_excel("2000~2024 조선일보/우울증_조선일보_20180101-20240930.xlsx", engine="openpyxl")[["제목","언론사","일자","키워드"]]
josun_df = pd.DataFrame(columns=["제목","언론사","일자","키워드"])


for name in lis:
    name_list = name.split("-")
    if name_list[1][0].isdigit()==False:
        name_list[0] = name_list[0] + "_" + name_list[1]
        del(name_list[1])
    article = name_list[0].split("/")[2]
    press = "조선일보"
    date = name_list[1].split("_")[0]
    if date[0].isdigit()==False:
        date = name_list[-1].split("_")[0]
        article = article + name_list[1].split("_")[0]
    date = re.sub("[^0-9]", "", date)
    article = re.sub("_", " ", article)
    f = open(name, 'r')
    text = f.read()
    tmp = pd.DataFrame({"제목": [article], 
                    "언론사": [press], 
                    "일자": [date],
                    "키워드": [text], 
                    })
    josun_df = pd.concat([josun_df, tmp])
    
josun_df = pd.concat([josun_df, xlsx])
    
josun_df.reset_index(inplace=True, drop=True)
josun_df.head(10)

,제목,언론사,일자,키워드
0,건강 키워드 '면역력'을 잡아라,조선일보,20160215,면역력(免疫力)은 면역세포가 인체에 침입한 유해 물질을 무찌르는 힘을 말한다. 우리...
1,"LG, 2014 시즌 캡틴 이진영 유니폼 판매요...",조선일보,20140624,LG 트윈스가 팬들을 위해 '캡틴 유니폼'을 출시했다.\nLG는 2014 시즌 주장...
2,"마성의 드라마 '왕가네 식구들', 이제부터가 ...",조선일보,20131002,"[OSEN=권지영 기자] 이제 겨우 10회분을 방송했을 뿐인데, 시청률 30%대를 ..."
3,고영욱 진술로 본 의문점 세가지,조선일보,20130327,[OSEN=임영진 기자] 아동·청소년의성보호에관한법률을 위반한 혐의를 받고 있는 고...
4,"최은주, 정정아와 함께 쇼핑몰 CEO로 변신",조선일보,20081112,배우 최은주가 개그우먼 정정아와 함께 쇼핑몰 '2층코끼리'를 오픈해 화제다.\n최은...
5,[이 스타가 사는법] (6) '천사표 가수' 현숙,조선일보,20090424,'대한민국 모든 어르신들이 행복해지는 그날까지.' 가수 현숙은 '나눔의 삶'을 실천...
6,'하이킥3' 작가들이 밝히는 관전포인트 5,조선일보,20110919,MBC '하이킥! 짧은 다리의 역습'이 오늘(19일) 첫 공개된다.\n하반기 안방극...
7,"'살림남' 일라이, 요리도 청소도 완벽한 ...",조선일보,20170111,[스포츠조선닷컴 정안지 기자]'살림남' 일라이가 다정남의 끝판왕 면모를 선보였다.\...
8,"타이거JK, 우울증 앓는 팀원에게 남긴 후...",조선일보,20170821,엠넷의 '쇼미더머니6'에 프로듀서로 출연 중인 타이거JK가 우울증을 앓고 있는 자신...
9,"""퇴행성관절염, 한방(韓方)에 일어나자""",조선일보,20101005,▶한방의 약과 침 그리고 색채요법으로 심리치료 병행\n퇴행성관절염 환자 수가 매년 ...

In [7]:
bigkinds_df = pd.DataFrame()
lis = glob.glob('1990~2024 빅카인즈/*.xlsx')

for data in lis:
    tmp = pd.read_excel(data, engine="openpyxl")
    tmp = tmp[["제목","언론사","일자","키워드"]]
    bigkinds_df = pd.concat([bigkinds_df, tmp])
    
bigkinds_df.drop_duplicates(inplace=True)
bigkinds_df.reset_index(inplace=True, drop=True)
bigkinds_df.tail(20)

,제목,언론사,일자,키워드
56921,코...코...코스닥때문에 신종 두 증후군,한국일보,20000115,"코스닥때문,신종,증후군,주식시장,천당,지옥,증후군,가지,사회,증후군,원인,상반,증상..."
56922,[만남] 김강자 종압경찰서장-강지원 청소년보호위원장,한국일보,20000115,"김강자,종압,경찰,서장,강지원,청소년보호위원장,전쟁,싸움,싸움,싸움,가난,소외속,사..."
56923,중학생이 동급생에 1천1백여만원 뜯어,국민일보,20000114,"중학생,동급생,1천,경남,진주경찰서,13일,급우,상대,2년,하루,3만,6백,차례,1..."
56924,"""피노체트 석방 결정 정신건강 문제 때문""",국민일보,20000114,"피노체트,석방,결정,정신,건강,칠레,피노체트,독재자,아우구스토,귀국,보도,영국,언론..."
56925,"구오야마 노리히코씨, 위안부출신 할머니들 무료진료",동아일보,20000113,"구오야마,노리히코,무료진료,위안부,출신,할머니,무료,진료,일본인,정신,의사,구와야마..."
56926,중학생이 같은반 친구1명 협박 1100만원 갈취,동아일보,20000113,"중학생,친구,협박,갈취,중학생,1명,친구,2년,협박,1100여만,갈취,경남,진주경찰..."
56927,'교사 철학이 바뀌면 학교가 달라집니다',한겨레,20000113,"교사,철학,학교,교육일기,김은형교사,교사들,현장,믿음,고민,절망감,철학,교사,학생들..."
56928,'주식 중독증' 우울증 환자 늘고 있다,중앙일보,20000113,"주식,중독증,우울증,환자,과장,8시,신경,전화기,놨다,10여차례,줄담배,사무실,주식..."
56929,[미리보는 새천년]노화정복/넘치는 '백살청춘',동아일보,20000112,"노화정복,백살청춘,중국,진시황,秦始皇,불로초,50세,역사,만큼,고대,그리스인,평균수..."
56930,[월드 메디컬]머리 많이 쓰면 노화현상 막는다,동아일보,20000112,"머리,노화현상,나이,기억력감퇴,우울증,학습능력,저하,변화,도파민,호르몬,분비,로이터..."
56931,[유전자지도 완성 초읽기]난치병 치료 신기원 연다,동아일보,20000111,"난치병,치료,연다,작성,인간,유전자,지도,가능성,미국,생명,공학,회사,셀레라,제노믹..."
56932,[타임머신21] 거리에 '사이버 중독환자' 득실,중앙일보,20000111,"거리,사이버,중독,환자,득실,사람들,인터넷,공화국,사람,사이버,독립,선언문,가상공간..."
56933,함께 만드는 가족공동체 문화,국민일보,20000110,"가족,공동체,문화,가정,사랑,다툼,갈등,건설적,대화,세파,모판,현실,가정들,모습,거..."
56934,선교 연극인 윤향금씨 모노드라마 '거울' 카세트테이프 제작,국민일보,20000107,"선교,연극,거울,윤향금,모노드라마,카세트테이프,제작,선교연극,윤향금씨,갈보리교회,8..."
56935,[뉴욕타임스]음식역사 ＂지난 1000년은 맛보다 양＂,동아일보,20000103,"음식역사,1000년,1000년,인류,대다수,역사,식사,주목,사람들,상상력,미래,암시..."
56936,21세기에 뜨는 유망직업 21가지,경향신문,20000103,"21세기,유망,직업,가지,컴퓨터,중심,전문,업종,각광,직업,종사자,개개인,생존수단,..."
56937,화초 잘 키우면 약초 된답니다,한겨레,20000103,"화초,약초,새해,집안,분위기,실내,화초,식물,스트레스,해소,활성,도움,요즘,생활,겨..."
56938,[황세희기자에게 물어보세요] 칠순노모 맛 냄새 몰라,중앙일보,20000103,"칠순노모,냄새,칠순,노모,오랫동안,냄새,음식,결국,기력,주부,양천구,신정,노인,반찬..."
56939,[우리아이 어떡하죠?]류인균/'인터넷 자제력'키워야,동아일보,20000102,"류인균,인터넷,자제력,워야,청소년,전문가들,청소년,전문가,체험,바탕,칼럼,월요일,게..."
56940,겨울엔 고혈압.피부염 미리미리 조심,국민일보,20000101,"겨울,고혈압,피부염,조심,질병,계절,여름,전염,질환,저온건조,겨울,혈관,질환,계절별..."

In [9]:
df = pd.concat([df, jungang_df])
df = pd.concat([df, josun_df])
df = pd.concat([df, bigkinds_df])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69908 entries, 0 to 56940
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제목      69908 non-null  object
 1   언론사     69908 non-null  object
 2   일자      69908 non-null  object
 3   키워드     69908 non-null  object
dtypes: object(4)
memory usage: 2.7+ MB

In [10]:
df["text"] = df["키워드"].str.replace("[^가-힣|0-9]","", regex=True)
df.head(10)

,제목,언론사,일자,키워드,text
0,심프슨교수「高血壓(고혈압)의_藥物(약물)_요법」,경향신문,19791016,"['심프슨교수 「高血�(고혈압) 의 薬物 (약물) 요법」 \n', '빠른진단이 最善...",심프슨교수고혈압의약물요법빠른진단이최선의치료고혈압약선택은신중해야50대는3년에한번쯤은측...
1,갱년기엔_달리기-등산을,조선일보,19950113,"['갱년기엔 달리기-등산을 \n', '산소 섭취하는유산소운동과근력 증강시키는하중운동...",갱년기엔달리기등산을산소섭취하는유산소운동과근력증강시키는하중운동섞어서해야김창기기자갱년기...
2,불행한_가정은_질병_원인된다,조선일보,19960508,"['불행한 가정은 \n', '질병 원인된다 \n', '사별우울증 = 무력감 겪어 \...",불행한가정은질병원인된다사별우울증무력감겪어이혼정신질환확률6배독신기혼자보다사망률높아불화...
3,PC통신_안방마님_주부파워_막강,조선일보,19970517,"['PC통신 안방마님 \n', '주부파워 막강 \n', '매년 3배 증가··· 재테...",통신안방마님주부파워막강매년3배증가재테크육아등교류활발고주미기자강병태기자통신이주부네티즌...
4,주부頭痛(두통)82%가「마음의_病(병)」때문,동아일보,19830628,"['주부頭痛 (두통) 82%가 「마음의 病 (병)」 때문 \n', '夫婦 (부부) ...",주부두통82가마음의병때문부부불화남편음주고부갈등이유발의주인정확한진단없이진통제마구쓰면만...
5,“웃음은_人生(인생)의_힘”美(미)코미디언‘마ᄀ...,조선일보,19990930,"['""웃음은 人生 (인생) 의 힘""美 (미) 코미디언\'마거릿 조\'再起 (재기) ...",웃음은인생의힘미코미디언마거릿조재기내가살아남은건오직관객들덕분이에요죽어가고있다고느낄때도...
6,신경정신과_鄭聖德(정성덕)박사_설문조사_...,경향신문,19820621,"['신경정신과 �聖徳 (정성덕)박사 설문조사 \n', '主婦 (주부) 우울증이 늘고...",신경정신과정성덕박사설문조사주부우울증이늘고있다가족성격취미등남편과폭넓은대화통해이해를주부...
7,프랑스의_새_골칫거리_컴퓨터사고_人災(인재)ᄀ...,경향신문,19890401,"['프랑스의 새 골칫거리 컴퓨터사고 \n', '人災 (인재)가 대부분 \n', '人...",프랑스의새골칫거리컴퓨터사고인재가대부분인사불만등앙심입력내용파괴87년3만1천여건피해액1...
8,불새(474),조선일보,19800730,"['불새 \n', '(474) \n', '野 (야) 火 (화) 26 (㉖) \n',...",불새474야화26최인호우경희화미란은벽시계를쳐다보았다열두시가마악지나고있었다그는돌아오지...
9,청소년_우울증_논문발표,조선일보,19930304,"['청소년 우울증 논문발표 \n', '우리나라 어린이와 청소년들은미국학생들보다 우울...",청소년우울증논문발표우리나라어린이와청소년들은미국학생들보다우울증등정신장애를훨씬심하게겪는...

In [11]:
def tokenize(sentence:pd.Series):

    tokenizer = Mecab()
    tokenized=[]
    temp = tokenizer.nouns(sentence)
    temp = [word for word in temp] 
    tokenized.append(temp)
    
    for token in tokenized:
        string = ""
        for num in range(len(token)):
            if (len(token[num])>=2) & (num != len(token)-1):
                string += token[num] + ","
            elif num == len(token)-1:
                string += token[num]
    return string

In [12]:
df["키워드"] = df["text"].apply(tokenize)
df.drop("text", axis=1, inplace=True)

In [13]:
import pyBigKinds as pbk

pbk.keyword_dataframe(df).head(20)

     단어      빈도
0   우울증  107325
1    사람  106430
2    정신   89132
3    치료   85580
4    건강   73876
5    환자   64580
6    사회   62518
7    자살   61361
8    여성   57248
9    자신   55424
10   장애   55417
11   아이   51696
12   병원   51432
13   교수   43205
14   생각   41792
15   가족   40299
16   마음   39966
17   질환   39379
18   생활   39361
19   서울   37770

In [15]:
weighted = pbk.tfidf(df)
weighted.head(20)

      단어           빈도
0     정신  1524.390626
1     자살  1453.151427
2     치료  1425.526401
3     사람  1396.062827
4    우울증  1332.896460
5     환자  1290.072729
6     건강  1277.992554
7     여성  1139.440653
8     경찰  1096.523615
9     장애  1094.257294
10    아이  1028.510149
11    사회  1007.143056
12    병원   958.246577
13    자신   901.600813
14    교수   840.964428
15    조사   834.405323
16  스트레스   820.494152
17    질환   817.249739
18    가족   801.122647
19    마음   770.791516

In [ ]:
df.to_excel("model/data/depression_all.xlsx", index=False)