In [1]:
import glob
import pandas as pd
import re
from tqdm import tqdm
from konlpy.tag import Mecab

import warnings
warnings.filterwarnings("ignore")

In [4]:
lis = glob.glob('1960~1999 네이버 뉴스 라이브러리/Text(Upsgate OCR)/*.txt')
df = pd.DataFrame(columns=["제목","언론사","일자","키워드"])

for name in lis:
    name_list = name.split("_")
    article = name_list[0].split("/")[2]
    press = name_list[1].split("1")[0]
    date = re.sub("[^0-9]" ,"", name_list[1])
    f = open(name, 'r')
    text = str(f.readlines()[2:])
    tmp = pd.DataFrame({"제목": [article], 
                       "언론사": [press], 
                       "일자": [date],
                       "키워드": [text], 
                       })
    df = pd.concat([df, tmp])
    
df.reset_index(inplace=True, drop=True)
df.head(10)

,제목,언론사,일자,키워드
0,일영화개방은UIP직배재판,조선일보,19900527,"['日 (일) 영화개방은 UIP직배 再版 (재판)"" \n', '""청소년왜 색화- 邦..."
1,휴지통,동아일보,19620208,"['휴지통 \n', '▼·····6일 경 북금릉군 아포면석암동三二五 (삼이오) 에사..."
2,항생제비싼것일수록더해롭다,경향신문,19820305,"['항생제 비싼것일수록 더해롭다 \n', '각성제 長服 (장복) 하면 분열증 \n'..."
3,고문사라져야한다추방캠페인평생을괴롭ᄒ...,동아일보,19870121,"['拷問 (고문) 사라져야한다 \n', '追放 (추방)페인 \n', '平生 (평생)..."
4,정신병자로불기소주인아들날살한박,경향신문,19630427,"['精神病者 (정신병자)로不起訴 (불기소) \n', '主人 (주인) 아들�� (날살..."
5,도시주부56우울증초기증세,조선일보,19820624,"['도시主婦 (주부)56% \n', '우울증 초기증세 \n', 'YMCA �聖徳 (..."
6,시급한고교교육의재검토,동아일보,19800715,"['時急 (시급)한 高校教育 (고교교육)의 再検討 (재검토) \n', '며칠전 李奎..."
7,2008년엔우주관광이뤄진다,동아일보,19871009,"['""2008년엔 우주관광 이뤄진다"" \n', '日 (일) 과학기술자 3,000명대..."
8,뉴스센터일밤900,동아일보,19831203,"['뉴스 센터 \n', '<MBC 日 (일) 밤9.00> \n', '� (소)SS2..."
9,가정불화과중한학습부담어린이정신질ᄒ...,동아일보,19790418,"['가정不和 (불화) ·과중한 �習 (학습) 부담 \n', '어린이精神疾患 (정신질..."

In [6]:
lis = glob.glob('1960~1989 중앙일보/*.txt')
jungang_df = pd.DataFrame(columns=["제목", "언론사", "일자", "키워드"])

for name in lis:
    name_list = name.split("-")
    try:
        for _ in range(len(name_list)):
            if name_list[1][0].isdigit()==False:
                name_list[0] = name_list[0] + "_" + name_list[1]
                del(name_list[1])
    except:
       del(name_list[1])
    article = name_list[0].split("/")[1]
    press = "중앙일보"
    date = name_list[1].split("_")[0]
    if date[0].isdigit()==False:
        date = name_list[1].split("_")[1]
        article = article + name_list[1].split("_")[0]
    date = re.sub("[^0-9]", "", date)
    article = re.sub("_", " ", article)
    f = open(name, 'r')
    text = f.read()
    tmp = pd.DataFrame({"제목": [article], 
                       "언론사": [press], 
                       "일자": [date],
                       "키워드": [text], 
                       })
    jungang_df = pd.concat([jungang_df, tmp])
    
jungang_df.reset_index(inplace=True, drop=True)
jungang_df.head(10)

,제목,언론사,일자,키워드
0,「의식」과 함께 돌아온「사랑」,중앙일보,19680312,맑은정신을 잃었던 두남녀가 길고 지루한 투병끝에 「스위트·홈」을 꾸미고 새출발했다 ...
1,반대를 무릅쓰고 결혼,중앙일보,19860121,"□…KBS제1TV 『미니시리즈, 밤은 돌아오지 않는다』(21일 밤 9시45분) 제1..."
2,일 학계의 반응,중앙일보,19740821,▲「와다나베」<도변학·「무사시」(무장)대학 교수·잡지 「한」의 편집자>=어느 쪽에도...
3,「힝클리」무죄평결로 미국전체가 발칵 ...,중앙일보,19820623,대통령저격범에 무죄 평결―..\n미국전체가 다시 한번 발칵 뒤집히고 말았다.\n불과...
4,이것만은 근절하자,중앙일보,19840620,한동안 잠잠하던 히로뽕 상용행위가 다시 고개를 들고 있어 심각한 사회문제로 대두되고...
5,꿈은 타고난 성격의 녹음「테이프」,중앙일보,19790809,『악몽에 자주 시달리는 사람은 정신분열증에 걸릴지도 모른다』-이것은 최근 일본에서 ...
6,동방교와 허광공,중앙일보,19681219,한때 간음및 폭행사건등으로 말썽났던 동방교안에서 사상최대의 다액도난사건이 일어났다....
7,불안감에 시달리는 학생 많다.,중앙일보,19890320,봄과 더불어 새 학년과 새 학기가 시작되면서 새로운 환경에 적응하려는 초· 중· 고...
8,예비군에 기합 순경 한 명 구속,중앙일보,19700730,【부산】30일 경남 하동 경찰서는 금남면 지서 이보영 순경 (27) 을 폭행 치상 ...
9,재소자 맞아 숨진건 국가책임,중앙일보,19860619,서울고법민사2부(재판장 이재화부장판사)는 19일 재소자가 교도소안에서 동료재소자에게...

In [8]:
lis = glob.glob('2000~2024 조선일보/조현병/*.txt')
josun_df = pd.DataFrame(columns=["제목","언론사","일자","키워드"])

for name in lis:
    name_list = name.split("-")
    for i in range(1, len(name_list)+1):
        if name_list[1][0].isdigit()==False:
            checker = True
            name_list[0] = name_list[0] + "_" + name_list[1]
            del(name_list[1])
    article = name_list[0].split("/")[2]
    press = "조선일보"
    date = name_list[1].split("_")[0]
    if date[0].isdigit()==False:
        date = name_list[1].split("_")[1]
        article = article + name_list[1].split("_")[0]
    date = re.sub("[^0-9]", "", date)
    article = re.sub("_", " ", article)
    f = open(name, 'r')
    text = f.read()
    tmp = pd.DataFrame({"제목": [article], 
                       "언론사": [press], 
                       "일자": [date],
                       "키워드": [text], 
                       })
    josun_df = pd.concat([josun_df, tmp])
    
josun_df.reset_index(inplace=True, drop=True)
josun_df.head(10)

,제목,언론사,일자,키워드
0,정신증 조기발견·치료에 전 세계 27개국 ...,조선일보,20200915,국내에서는 서울대병원 권준수 연구팀 유일하게 참여\n1000여 명 환자 모집해 임상...
1,정신병원 입원시켰다 며 모친 살해한 ...,조선일보,20190904,부모가 자신을 강제로 정신병원에 입원시켰다 생각해 아버지를 폭행하고 어머니를 살해한...
2,[Oh!쎈 컷] 괜사 → 7호실 도경수표 청춘...,조선일보,20171101,[OSEN=지민경 기자] 신하균과 도경수의 만남으로 주목을 받은 영화 '7호실'에서...
3,"9.11 테러범, 감옥에서 해리포터 읽고 진고...",조선일보,20130712,미국 중앙정보국(CIA)이 9·11 테러범 칼리드 셰이크 모하메드의 정신 이상을 막...
4,"선풍기 아줌마 한혜경씨, 15일 별세…향...",조선일보,20181217,불법 성형 부작용으로 얼굴이 크게 부풀어 '선풍기 아줌마'로 불린 한혜경 씨가 최근...
5,[김민철의 뉴스 저격] 조현병 환자 입원...,조선일보,20191025,조현병을 앓는 여성 A(37)씨는 지난 20일 저녁 7시쯤 대전 대덕구 집에서 어머...
6,[Why] 토파즈 빛으로 튀는 레몬의 향기,조선일보,20071130,애타도록 당신은 레몬을 찾고 있었다.\n\n죽음의 슬프고도 화려한 병상에서\n\n내...
7,아파트 방화살인 안인득 사형 선고… 배...,조선일보,20191128,자신이 살던 아파트에 불을 지른 뒤 대피하던 주민 5명을 살해한 혐의 등으로 구속기...
8,[역사 속 숨은 영웅] 화려한 삶 버리고 ᄇ...,조선일보,20160725,1930년대에 중국에서 활동한 영화배우로 '영화 황제'라 불렸다. 주요 작품은 '도...
9,부천서 정신건강 영화제,조선일보,20061101,오는 9일과 24일 부천에서 이색적인 영화제가 열린다. '정신 건강 영화제'다. 일...

In [10]:
bigkinds_df = pd.DataFrame()
lis = glob.glob('1990~2024 빅카인즈/*.xlsx')

for data in lis:
    tmp = pd.read_excel(data, engine="openpyxl")
    tmp = tmp[["제목","언론사","일자","키워드"]]
    bigkinds_df = pd.concat([bigkinds_df, tmp])
    
bigkinds_df.drop_duplicates(inplace=True)
bigkinds_df.reset_index(inplace=True, drop=True)
bigkinds_df.head(20)

,제목,언론사,일자,키워드
0,“휴대전화 좀 보자”는 아버지에게 찾아온 비극 아들은 ‘심신 상실’ 주장,세계일보,20240911,"휴대전화,아버지,비극,아들,심신,상실,주장,휴대전화,전화기,친부,흉기,살해,혐의,재..."
1,내 옆의 그 사람도 병원서 묶여 죽었다,한겨레,20240709,"사람,병원,그날,물속,느낌,세상,마지막,찰나,따위,선착장,한남대교,인근,안경,신발,..."
2,"조현병 중 ‘상세불명 조현병’ 삭발한 머리 위로 미용사 눈물 뚝, 뚝",한겨레,20240207,"조현병,불명,조현병,삭발,머리,미용사,눈물,조현병,조현,調絃,현악기,치료,현악기,소..."
3,"“엄벌제도보다 필요한 건, 범죄자 100% 처벌받는다는 법의 확실성”[논설위원의 단...",경향신문,20230829,"엄벌제도,처벌,범죄자,100%,논설위원,단도직입,선임연구위원,김지선,형사,정책,선임..."
4,‘심신미약’을 악용하는 범죄자에게 울리는 경종[플랫],경향신문,20230623,"심신미약,악용,범죄자,경종,플랫,형사,정신,감정,오해,감경,제도,범죄,처벌,심신미약..."
5,“부산 돌려차기남과 정유정은 심신미약 아니다”[논설위원의 단도직입],경향신문,20230620,"부산,정유정,심신,미약,논설위원,단도직입,전문의,차승민,정신,건강,의학,충남대,의과..."
6,중국을 뒤흔든 ‘쇠사슬녀’ 남편에 징역 9년 “너무 가볍다”,서울신문,20230408,"중국,쇠사슬녀,남편,징역,중국인들,충격,쇠사슬녀,사건,가해자,남편,둥즈민,징역,선고..."
7,“악마가 보인다” 어머니 살해한 40대 구속,세계일보,20230124,"악마,어머니,살해,구속,조현증,아들,악마,어머니,사건,발생,경찰,어머니,살해,혐의,..."
8,"“‘코로나 회복’ 백신 미접종자, 재감염 위험 접종자보다 5배↑”",세계일보,20211030,"코로나,회복,백신,미접종자,접종자,재감염,위험,5배,8월,캘리포니아,LA,클리닉,Y..."
9,"美CDC, 우울증 등 정신질환도 코로나 부스터샷 접종요건에 추가",세계일보,20211030,"CDC,우울증,정신질환,접종요건,코로나,부스터,접종,요건,추가,미국,질병,통제,예방..."
10,"레이디 가가 “열아홉살 때 성폭행 후 임신, 완전 망가져”",서울신문,20210521,"레이디,성폭행,임신,완전,해리,왕자,엄마,다이애나빈,약물,의존,미국,팝스타,레이디,..."
11,윤형빈 ‘폭행 방조 의혹’ 수사 착수 개그맨 지망생 “녹취록 등 증거 有”,세계일보,20201218,"윤형빈,폭행,방조,의혹,수사,착수,개그맨,지망,녹취록,증거,개그맨,윤형빈,40,폭언..."
12,"경찰, 개그맨 윤형빈 고소건 수사 진행",중앙일보,20201218,"경찰,진행,개그맨,윤형빈,고소건,수사,방송인,윤형빈,개그맨,지망,폭언,폭행,방관,의..."
13,윤형빈 측 “집단괴롭힘 방조 사실무근 추가 고소할 것”,세계일보,20201218,"윤형빈,집단,윤형빈,방조,사실무근,추가,고소,개그맨,윤형빈,개그맨,지망,폭언,방관,..."
14,윤형빈 측 “개그맨 지망생 폭행 방조 의혹? 사실무근 오히려 수차례 협박당해”,세계일보,20201217,"윤형빈,사실무근,수차례,협박,개그맨,윤형빈,40,17일,온라인,커뮤니티,제기,폭언,..."
15,"“오히려 협박당했다” 윤형빈, 개그지망생 폭행 방조 의혹 해명",국민일보,20201217,"협박,윤형빈,해명,개그,지망,폭행,방조,의혹,코미디언,윤형빈,17일,온라인,커뮤니티..."
16,"윤형빈, 개그지망생 폭행 방조 의혹에 ""사실무근 추가 고소 진행""",중앙일보,20201217,"윤형빈,개그,지망,폭행,방조,의혹,사실무근,추가,고소,진행,코미디언,윤형빈,개그맨,..."
17,中 정신병원서 임신해 퇴원한 23살女 병원 측 “쌍방 합의”,국민일보,20201115,"정신,임신,퇴원,23살,병원,합의,쌍방,중국,지적,장애,여성,폐쇄,정신,병원,입원,..."
18,"“정신장애인 낙인, 사회적 관계 맺을수록 줄어들어”",한겨레,20200325,"정신,장애인,낙인,사회적,정신질환,혐오,대상,동시,극단적,방식,제거,대상,정신장애인..."
19,[김창기의 음악상담실]지금 내 나이는 ‘봄’이다,동아일보,20190406,"나이,사이먼&가펑클,Come,4월,냇물,봄비,봄기운,레드,제플린,Stairway,h..."

In [29]:
df = pd.concat([df, jungang_df])
df = pd.concat([df, josun_df])
df = pd.concat([df, bigkinds_df])
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10630 entries, 0 to 8442
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제목      10630 non-null  object
 1   언론사     10630 non-null  object
 2   일자      10630 non-null  object
 3   키워드     10630 non-null  object
dtypes: object(4)
memory usage: 415.2+ KB

In [30]:
df["text"] = df["키워드"].str.replace("[^가-힣|0-9]","", regex=True)
df.head(10)

,제목,언론사,일자,키워드,text
0,일영화개방은UIP직배재판,조선일보,19900527,"['日 (일) 영화개방은 UIP직배 再版 (재판)"" \n', '""청소년왜 색화- 邦...",일영화개방은직배재판청소년왜색화방화파멸서울서토론모임당국의부인에도불구노태우대통령의방일을...
1,휴지통,동아일보,19620208,"['휴지통 \n', '▼·····6일 경 북금릉군 아포면석암동三二五 (삼이오) 에사...",휴지통6일경북금릉군아포면석암동삼이오에사는황순분12양의친권자황월동52씨가이옷김상학50...
2,항생제비싼것일수록더해롭다,경향신문,19820305,"['항생제 비싼것일수록 더해롭다 \n', '각성제 長服 (장복) 하면 분열증 \n'...",항생제비싼것일수록더해롭다각성제장복하면분열증강간제잘못복용하면되려악화서울대김낙두교수의약...
3,고문사라져야한다추방캠페인평생을괴롭ᄒ...,동아일보,19870121,"['拷問 (고문) 사라져야한다 \n', '追放 (추방)페인 \n', '平生 (평생)...",고문사라져야한다추방페인평생을괴롭히는후유증늑막염신경통에무력감도15년지난지금까지지팡이없...
4,정신병자로불기소주인아들날살한박,경향신문,19630427,"['精神病者 (정신병자)로不起訴 (불기소) \n', '主人 (주인) 아들�� (날살...",정신병자로불기소주인아들날살한박27일상오서울지검김성진검사는재워주지않는다는이유로주인집아...
5,도시주부56우울증초기증세,조선일보,19820624,"['도시主婦 (주부)56% \n', '우울증 초기증세 \n', 'YMCA �聖徳 (...",도시주부56우울증초기증세정성덕박사밝혀가족사이인격대화모자라35세안팎에가장많은분포신경질...
6,시급한고교교육의재검토,동아일보,19800715,"['時急 (시급)한 高校教育 (고교교육)의 再検討 (재검토) \n', '며칠전 李奎...",시급한고교교육의재검토며칠전이규호문교부장관은심각한사회문제가되고있는과열과외의부작용을망국...
7,2008년엔우주관광이뤄진다,동아일보,19871009,"['""2008년엔 우주관광 이뤄진다"" \n', '日 (일) 과학기술자 3,000명대...",2008년엔우주관광이뤄진다일과학기술자3000명대상미래예측조사암당뇨병등정복자기부상열차...
8,뉴스센터일밤900,동아일보,19831203,"['뉴스 센터 \n', '<MBC 日 (일) 밤9.00> \n', '� (소)SS2...",뉴스센터일밤900소20극동배치의파장뉴스센터가공할핵미사일20극동에배치될20핵미사일1백...
9,가정불화과중한학습부담어린이정신질ᄒ...,동아일보,19790418,"['가정不和 (불화) ·과중한 �習 (학습) 부담 \n', '어린이精神疾患 (정신질...",가정불화과중한학습부담어린이정신질환유발한다아동정신과권위로코모토교수에듣는다가장많은증상은...

In [31]:
def tokenize(sentence:pd.Series):

    tokenizer = Mecab()
    tokenized=[]
    temp = tokenizer.nouns(sentence)
    temp = [word for word in temp] 
    tokenized.append(temp)
    
    for token in tokenized:
        string = ""
        for num in range(len(token)):
            if (len(token[num])>=2) & (num != len(token)-1):
                string += token[num] + ","
            elif num == len(token)-1:
                string += token[num]
    return string

In [32]:
df["키워드"] = df["text"].apply(tokenize)
df["일자"] = pd.to_datetime(df["일자"])
df.drop("text", axis=1, inplace=True)

In [33]:
import pyBigKinds as pbk

pbk.keyword_dataframe(df).head(20)

     단어     빈도
0    정신  47820
1    환자  23711
2    치료  20013
3    사람  14244
4    병원  13352
5    사회  12969
6    장애  12707
7    질환  11323
8    경찰  11029
9    조현  10686
10   사건   9504
11   건강   9259
12   자신   8483
13   여성   8007
14   입원   7805
15   범행   7748
16  분열증   7495
17   가족   6676
18   범죄   6381
19   교수   6215

In [35]:
weighted = pbk.tfidf(df)
weighted.head(20)

    단어          빈도
0   정신  551.040619
1   환자  397.458428
2   치료  337.686128
3   경찰  315.240895
4   범행  260.248958
5   병원  252.453328
6   장애  243.482241
7   조현  223.779953
8   질환  219.513705
9   사회  205.472422
10  사람  204.155508
11  사건  200.257482
12  입원  190.152475
13  흉기  187.162238
14  여성  186.767702
15  건강  186.088309
16  혐의  180.091604
17  선고  169.326296
18  범죄  161.446318
19  자신  159.281404

In [ ]:
df.to_excel("../../model/data/schizophrenia_all.xlsx", index=False)